# 应用服务 WEB 访问端口
server:
  port : 8082
  
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465
    username: 2486722561@qq.com
    password: nvbaozzvyysseadb
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wW123456..
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.3.91:3306/paper_sword?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    database: 0
    host: 49.234.3.91
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 200
        max-idle: 16
        min-idle: 8
        max-wait: 1000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: paper-sword-user
  registry:
    address: zookeeper://49.234.3.91:2181
  #    address: N/A
  protocol:
    name: dubbo
    port: 20881
  consumer:
    timeout: 60000
    retries: 0
elasticsearch:
  hostname: 49.234.3.91
  port: 9200