server:
  port: 8080

# 应用名称
spring:
  elasticsearch:
    rest:
      uris: 49.234.3.91:9200
  application:
    name: paper-sword

  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wW123456..
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.3.91:3306/paper_sword?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    database: 0
    host: 49.234.3.91
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 200
        max-idle: 16
        min-idle: 8
        max-wait: 1000
    password: 123456

dubbo:
  application:
    name: paper-sword-gateway
  registry:
    address: zookeeper://49.234.3.91:2181
  consumer:
    timeout: 60000
    retries: 0
logging:
  level:
    root: info
elasticsearch:
  hostname: 49.234.3.91
  port: 9200


